Revert "[InfoBarPiP] showPiP() code improvement (#3525)"
This reverts commit b46b91b6231d0823c5d9032a288f7609ef2c9370.

BSOD:
05:08:05.3425 AttributeError: 'Session' object has no attribute 'pipshown'
05:08:05.3426 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xb221e2d0>>,('GlobalActions', 'power_up')) failed)